// frontend/src/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router'
import { Toaster } from 'vue-sonner'
import { useThemeStore } from './stores/theme'
import { useAuthStore } from './stores/auth'
import { onMounted } from 'vue'

const themeStore = useThemeStore()
const authStore = useAuthStore()

onMounted(() => {
  themeStore.init()
  authStore.init()
})
</script>

<template>
  <RouterView />
  <Toaster position="top-center" rich-colors />
</template>

// Support Community App/src/app/App.tsx
import { RouterProvider } from 'react-router';
import { router } from './routes';
import { Toaster } from './components/ui/sonner';
import { ThemeProvider } from './contexts/theme-context';

export default function App() {
  return (
    <ThemeProvider>
      <RouterProvider router={router} />
      <Toaster position="top-center" />
    </ThemeProvider>
  );
}
