// frontend/src/components/community/EmptyState.vue
<script setup lang="ts">
import type { Component } from 'vue'

defineProps<{
  icon?: Component
  title?: string
  description?: string
}>()
</script>

<template>
  <div class="flex flex-col items-center justify-center py-16 text-center">
    <div v-if="$props.icon" class="w-16 h-16 rounded-full bg-secondary flex items-center justify-center mb-4">
      <component :is="$props.icon" class="w-8 h-8 text-muted-foreground" />
    </div>
    <p class="font-medium mb-2">{{ title || '暂无内容' }}</p>
    <p class="text-sm text-muted-foreground">{{ description }}</p>
    <slot />
  </div>
</template>

// Support Community App/src/app/components/community/empty-state.tsx
import { LucideIcon } from 'lucide-react';

interface EmptyStateProps {
  icon: LucideIcon;
  title: string;
  description?: string;
  action?: React.ReactNode;
}

export function EmptyState({ icon: Icon, title, description, action }: EmptyStateProps) {
  return (
    <div className="flex flex-col items-center justify-center py-16 px-6 text-center">
      <div className="w-20 h-20 rounded-full bg-secondary flex items-center justify-center mb-4">
        <Icon className="w-10 h-10 text-primary" />
      </div>
      <h3 className="mb-2">{title}</h3>
      {description && (
        <p className="text-muted-foreground mb-6 max-w-sm">{description}</p>
      )}
      {action}
    </div>
  );
}
