// frontend/src/components/community/LoadingState.vue
<script setup lang="ts">
import Skeleton from '@/components/ui/Skeleton.vue'
</script>

<template>
  <div class="space-y-3 py-2">
    <div v-for="i in 3" :key="i" class="bg-card rounded-2xl p-5 border border-border/50">
      <div class="flex items-center gap-3 mb-3">
        <Skeleton class="w-8 h-8 rounded-full" />
        <div class="flex-1">
          <Skeleton class="h-3 w-24 mb-1" />
          <Skeleton class="h-2.5 w-16" />
        </div>
      </div>
      <Skeleton class="h-3 w-full mb-2" />
      <Skeleton class="h-3 w-4/5 mb-2" />
      <Skeleton class="h-3 w-3/5" />
    </div>
  </div>
</template>

// Support Community App/src/app/components/community/loading-state.tsx
export function LoadingState() {
  return (
    <div className="flex flex-col items-center justify-center py-16 px-6">
      <div className="relative w-12 h-12">
        <div className="absolute inset-0 rounded-full border-4 border-secondary"></div>
        <div className="absolute inset-0 rounded-full border-4 border-primary border-t-transparent animate-spin"></div>
      </div>
      <p className="text-muted-foreground mt-4">加载中...</p>
    </div>
  );
}

export function LoadingSkeleton() {
  return (
    <div className="space-y-3">
      {[1, 2, 3].map((i) => (
        <div key={i} className="bg-card rounded-2xl p-4 border border-border/50 animate-pulse">
          <div className="flex items-center mb-3">
            <div className="w-10 h-10 rounded-full bg-secondary"></div>
            <div className="ml-3 flex-1">
              <div className="h-4 bg-secondary rounded w-24 mb-2"></div>
              <div className="h-3 bg-secondary rounded w-16"></div>
            </div>
          </div>
          <div className="space-y-2">
            <div className="h-4 bg-secondary rounded w-full"></div>
            <div className="h-4 bg-secondary rounded w-4/5"></div>
          </div>
        </div>
      ))}
    </div>
  );
}
